#! /usr/bin/env python3
import sys
import json
import requests
import os

identity_url = (
    "https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig"
)


def get_project_config(api_key):
    try:
        response = requests.get(
            identity_url,
            headers={"Accept": "application/json"},
            params={"key": api_key},
            timeout=10,
        )
    except requests.exceptions.RequestException as e:
        return 500, {
            "error": {
                "message": str(e),
            }
        }

    try:
        return response.status_code, response.json()
    except json.JSONDecodeError:
        return response.status_code, {
            "error": {
                "message": "Could not decode JSON",
                "response": response.text,
            }
        }


def analyze_google_api_key(api_key):
    status_code, data = get_project_config(api_key)
    valid = status_code in (200, 403)
    print(json.dumps({"valid": valid, "analysis": data}, indent=2))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage:\n    analyze-google-api-key <api_key>")
        sys.exit(1)

    api_key_to_check = sys.argv[1]
    analyze_google_api_key(api_key_to_check)
