#!/usr/bin/env python3

import base64
import json
import os
import sys

import requests

from requests.exceptions import RequestException

USAGE = f"""
USAGE:
    {os.path.basename(sys.argv[0])} <containers-auth-json-filepath>
    {os.path.basename(sys.argv[0])} <hostname> <auth>
    {os.path.basename(sys.argv[0])} <hostname> <username> <password>

DESCRIPTION
    Analyze container registry auth by any of these methods:

    1) Reading a containers-auth.json file
    2) Accepting hostname and auth (i.e. base64(username:password))
    3) Accepting hostname, username, and password

    The containers-auth.json option will analyze all auths in the file and print
    the results out in the order that they appear in the file.
"""


def with_error(result, message, **kwargs):
    """
    return a copy of the result with error info added
    """
    return result | {
        "error": {
            "message": message,
            **kwargs,
        }
    }


def auth_info_creds(auth_info):
    encoded_token = auth_info.get("auth")
    if encoded_token:
        try:
            token = base64.b64decode(encoded_token).decode("utf-8")
        except Exception as e:
            raise ValueError("could not decode token") from e

        username, password = token.split(":", 1)
    elif "username" in auth_info and "password" in auth_info:
        username = auth_info["username"]
        password = auth_info["password"]
    else:
        raise ValueError("could not find auth information")

    return username, password


def analyze_auth_info(host, auth_info):
    """
    perform analyzis on each auth_info
    """
    analysis = {
        "host": host,
    }
    result = {
        "valid": False,
        "analysis": analysis,
    }

    if "email" in auth_info:
        analysis["email"] = auth_info["email"]

    try:
        username, password = auth_info_creds(auth_info)
    except Exception as e:
        return with_error(result, str(e))

    analysis["username"] = username
    params = {}

    if "docker" in host:
        url = "https://auth.docker.io/token"
    elif "quay" in host:
        url = f"https://{host}/v2/auth"
    elif "redhat" in host:
        url = "https://sso.redhat.com/auth/realms/rhcc/protocol/redhat-docker-v2/auth"
        params = {
            "service": "docker-registry",
            "client_id": "validate-token",
            "scope": "repository:rhel:pull",
        }

    else:
        url = f"https://{host}/v2"
    try:
        resp = requests.get(
            url,
            auth=(username, password),
            allow_redirects=True,
            params=params,
            timeout=10,
        )
    except RequestException:
        return with_error(result, "request failed")

    match resp.status_code:
        case 200:
            result["valid"] = True
        case _:
            return with_error(
                result,
                "request failed",
                status_code=resp.status_code,
            )

    return result


def analyze(config):
    for host, auth_info in config["auths"].items():
        yield analyze_auth_info(host, auth_info)


if __name__ == "__main__":
    match len(sys.argv):
        case 2:  # <containers-auth-json-filepath>
            with open(sys.argv[1]) as containers_auth_json_file:
                config = json.load(containers_auth_json_file)
        case 3:  # <hostname> <auth>
            config = {"auths": {sys.argv[1]: {"auth": sys.argv[2]}}}
        case 4:  # <hostname> <username> <password>
            config = {
                "auths": {
                    sys.argv[1]: {"username": sys.argv[2], "password": sys.argv[3]}
                }
            }
        case _:
            print(USAGE, file=sys.stderr)
            sys.exit(1)

    for result in analyze(config):
        print(json.dumps(result, indent=2))
