#!/usr/bin/env python3

import base64
import json
import os
import sys

import requests

from requests.exceptions import RequestException

USAGE = f"""
USAGE:
    {os.path.basename(sys.argv[0])} <containers-auth-json-filepath>
    {os.path.basename(sys.argv[0])} <hostname> <auth>
    {os.path.basename(sys.argv[0])} <hostname> <username> <password>

DESCRIPTION
    Analyze container registry auth by any of these methods:

    1) Reading a containers-auth.json file
    2) Accepting hostname and auth (i.e. base64(username:password))
    3) Accepting hostname, username, and password

    The containers-auth.json option will analyze all auths in the file and print
    the results out in the order that they appear in the file.
"""


def with_error(result, message, **kwargs):
    """
    return a copy of the result with error info added
    """
    return result | {
        "error": {
            "message": message,
            **kwargs,
        }
    }


def enrich_auth_info(auth_info):
    auth = auth_info.get("auth")
    if auth:
        try:
            auth = auth.rstrip('=')
            auth += '=' * (-len(auth) % 4)

            # janky b64 that we're just going to drop the last char on to see
            # what we can recover from it
            if auth.endswith('==='):
                auth = auth[:-4]

            user_pass = base64.b64decode(auth).decode(errors='ignore').split(":", 1)
        except Exception as e:
            raise ValueError("could not decode token") from e

        if len(user_pass) == 2:
            auth_info["username"] = user_pass[0]
            auth_info["password"] = user_pass[1]
        else:
            auth_info["username"] = ""
            auth_info["password"] = ""

    elif "username" in auth_info and "password" in auth_info:
        username = auth_info["username"]
        password = auth_info["password"]
        user_col_pass = f"{username}:{password}".encode("UTF-8")
        auth_info["auth"] = base64.b64encode(user_col_pass).decode(errors='ignore')
    else:
        raise ValueError("could not find auth information")

    return auth_info


def analyze_auth_info(host, auth_info):
    """
    perform analyzis on each auth_info
    """
    analysis = {
        "host": host,
    }
    result = {
        "valid": False,
        "analysis": analysis,
    }

    auth_info = enrich_auth_info(auth_info)
    analysis.update(auth_info)
    params = {}

    if "docker" in host:
        url = "https://auth.docker.io/token"
    elif "quay" in host:
        url = f"https://{host}/v2/auth"
    elif "redhat" in host:
        url = "https://sso.redhat.com/auth/realms/rhcc/protocol/redhat-docker-v2/auth"
        params = {
            "service": "docker-registry",
            "client_id": "validate-token",
            "scope": "repository:rhel:pull",
        }

    else:
        url = f"https://{host}/v2"
    try:
        resp = requests.get(
            url,
            allow_redirects=True,
            params=params,
            timeout=10,
            headers={
                "Authorization": f"Basic {auth_info['auth']}",
            },
        )
    except RequestException:
        return with_error(result, "request failed")

    match resp.status_code:
        case 200:
            result["valid"] = True
        case _:
            return with_error(
                result,
                "request failed",
                status_code=resp.status_code,
            )

    return result


def analyze(config):
    for host, auth_info in config["auths"].items():
        yield analyze_auth_info(host, auth_info)


if __name__ == "__main__":
    flags = {}
    args = []
    argv = iter(sys.argv[1:])

    for arg in argv:
        if arg.startswith("--"):
            key = arg[2:]
            if "=" in key:
                key, value = key.split("=", 1)
            else:
                value = next(argv)

            flags[key] = value
        else:
            args.append(arg)

    match len(args):
        case 1:  # <containers-auth-json-filepath>
            with open(args[0]) as containers_auth_json_file:
                config = json.load(containers_auth_json_file)
        case 2:  # <hostname> <auth>
            config = {"auths": {args[0]: {"auth": args[1]}}}
        case 3:  # <hostname> <username> <password>
            config = {"auths": {args[0]: {"username": args[1], "password": args[2]}}}
        case _:
            print(USAGE, file=sys.stderr)
            sys.exit(1)

    for result in analyze(config):
        if "format" not in flags:
            print(json.dumps(result, indent=2))
        else:
            print(flags["format"].format(**result))
