#!/usr/bin/env python3
import json
import os
import sys

from http import HTTPStatus

import requests

__doc__ = f"""
USAGE
    {os.path.basename(__file__)} <webhook-url>
"""


def error(message, **kwargs):
    return {"message": message, **kwargs}


def analyze(webhook_url):
    results = {
        "valid": False,
    }

    try:
        resp = requests.post(webhook_url, json={"text": "validating webhook"})
        results["valid"] = "error" not in resp.text
    except requests.exceptions.RequestException as e:
        results["error"] = error(f"request failed: {e}")

    return results


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)

    print(json.dumps(analyze(*sys.argv[1:])))
