#! /usr/bin/env python3

import base64
import json
import requests
import sys



def decode_jwt_part(part_str):
    try:
        decoded_bytes = base64.urlsafe_b64decode(part_str + "==")
        return json.loads(decoded_bytes.decode("utf-8"))
    except Exception as e:
        print(f"Error decoding JWT part: {e}", file=sys.stderr)
        return None



def analyze(base_url, token):
    headers = {
        "X-Secret-Key": "apiKey",
        "Image-Token": "apiKey",
        "Content-Type": "application/json",
        "Authorization": f"Bearer {token}",
    }

    if not base_url.startswith("http"):
        base_url = "https://" + base_url

    claims = decode_jwt_part(token.split(".")[1])
    result = {"valid": False, "analysis": claims}
    infra_env_id = claims["infra_env_id"]
    api_url = f"{base_url}/api/assisted-install/v2/infra-envs/{infra_env_id}"
    # image_api_url /byapikey/{token}/4.20/x86_64/minimal.iso
    # image_api_url /bytoken/{token}/4.20/x86_64/minimal.iso
    result["analysis"]["api_url"] = api_url

    try:
        response = requests.get(api_url, headers=headers, timeout=15, verify=False)
        match response.status_code:
            case 200:
                result["valid"] = True
                result["analysis"].update(response.json())
            case 401:
                result["analysis"]["error"] = response.json()
            case 403:
                result["analysis"]["error"] = response.json()
            case status_code:
                result["analysis"]["error"] = {
                    "message": f"Unexpected Status Code",
                    "data": response.text[:500].strip(),
                    "code": status_code,
                }
    except requests.exceptions.RequestException as e:
        result["analysis"]["error"] = str(e)

    return result


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("USAGE:\n\tanalyse-openshift-assisted-installer-token <hostname> <token>")
        sys.exit(1)

    hostname = sys.argv[1]
    token_value = sys.argv[2]
    print(json.dumps(analyze(hostname, token_value), indent=2))
