#!/usr/bin/env python3

import sys
import re
import ipaddress

ip_addr_re = re.compile(
    r"\b(?:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|(?:[0-9a-fA-F]{1,4}:{1,2}){1,7}(?:[0-9a-fA-F]{1,4}){1,7}\b"
)


def is_valid_ip_addr(address: str) -> bool:
    """
    Checks if a given string is a valid IPv6 address using the
    ipaddress standard library.
    """
    try:
        ipaddress.ip_address(address)
        return True
    except ValueError:
        return False


def main():
    found = set()
    for line in sys.stdin:
        found |= set(filter(is_valid_ip_addr, ip_addr_re.findall(line)))

    print("\n".join(sorted(found)))


if __name__ == "__main__":
    main()
