#! /usr/bin/env python3
"""
USAGE
    find-domains < some-file.txt

DESCRIPTION
    Return a unique list of resolvable domains found in a file
"""

import re
import sys
import socket

domain_re = re.compile(r"\b[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}\b")


def valid(domain):
    try:
        return len(socket.gethostbyname(domain)) > 0
    except:
        return False


if __name__ == "__main__":
    found = tuple(filter(valid, sorted(set(domain_re.findall(sys.stdin.read())))))
    print("\n".join(found))
