#! /usr/bin/env bash
set -euo pipefail
api_token="$1"

curl -s -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${api_token}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/user | jq
