#!/usr/bin/env bash
set -euo pipefail

rm -rf data
mkdir -p data/{images,texts}

ffmpeg -i "$2" -vf fps=1 data/images/second-%04d.png >&2

for img in data/images/*; do
    tesseract "$img" "data/texts/$(basename "$img" .png)" -l eng >&2
done

rg "$1" data/texts
