#! /usr/bin/env python3

"""
NAME
    leaktk-remove-files

USAGE
    leaktk scan --kind Files --resource . | leakkt-remove-files .

DESCRIPTION

    Removes files found in leaktk file scans scans

OPTIONS

    The first option to the command is the base path for the scan
"""

import json
import sys
import os


def main():
    """
    Main loops through the results from stdin and removes the files
    """
    exit_status = 0

    for response in map(json.loads, sys.stdin):
        basepath = sys.argv[1]

        for result in response["results"]:
            path = os.path.join(basepath, result["location"]["path"])
            description = result["rule"]["description"]
            line = result["location"]["start"]["line"]

            if os.path.exists(path):
                print(f"removed file: path={path}#L{line} description={description}")

                try:
                    os.unlink(path)
                except Exception as e:
                    print(
                        f"could not remove file: path={path}#L{line} description={description} error={e}"
                    )
                    exit_status = 2

    return exit_status


if __name__ == "__main__":
    sys.exit(main())
