#!/usr/bin/env python3

import sys
from minio import Minio

if __name__ == "__main__":
    try:
        client = Minio(
            sys.argv[1], access_key=sys.argv[2], secret_key=sys.argv[3], secure=True
        )
        print("buckets:", file=sys.stderr)
        print("".join([f"  - {s}\n" for s in client.list_buckets()]), file=sys.stderr)
        print("valid")
        sys.exit(0)
    except Exception:
        print("invalid")
        sys.exit(1)
