#!/usr/bin/env python3
import requests
import json
import sys

resp = requests.post(
    "https://api.github.com/credentials/revoke",
    headers={
        "X-GitHub-Api-Version": "2022-11-28",
        "Accept": "application/vnd.github+json",
    },
    json={"credentials": sys.argv[1:]},
)

if resp.status_code == 202:
    print(json.dumps({"status": "revoked", "credentials": sys.argv[1:]}, indent=2))
else:
    print(json.dumps(resp.json(), indent=2))
